version: "3.8"
services:
  flask-app:
    build: .
    ports:
      - "5001:5000"  # Maps the container's internal port 5000 to host's port 5001
    expose:
      - "5000"  # Makes port 5000 accessible within the internal Docker network
    restart: unless-stopped
    environment:
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}  # Fetches the value from .env

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}  # Use the token from .env
    depends_on:
      - flask-app  # Ensures the Flask app is started before Cloudflared
    environment:
      TUNNEL_SERVICE: "http://flask-app:5000"  # Points to the Flask app's internal service
    restart: unless-stopped
